train:
  num_experts: 5
  latent_dim: 32
  epochs: 20
  test_flag: false
  dataset: quickdraw  # Default dataset
  results_dir_suffix: ""  # Suffix for results directory
  batch_size: 128  # Default batch size
  learning_rate: 0.001  # Default learning rate
  beta: 0.01  # Default weight for KL divergence term
  load_balancing_coeff: 200.0  # Default weight for load balancing loss
  entropy_coeff: 400.0  # Default weight for entropy term
  model_size: 'lite'
  dataset_percentage: 1.0
  encoder_size: 'medium'
debug:
  num_experts: 1
  latent_dim: 16
  epochs: 1
  test_flag: true
  dataset: mnist  # Default dataset
  results_dir_suffix: ""  # Suffix for results directory
  batch_size: 128  # Default batch size
  learning_rate: 0.001  # Default learning rate
  beta: 1.0  # Default weight for KL divergence term
  load_balancing_coeff: 1  # Default weight for load balancing loss
  entropy_coeff: 1.0  # Default weight for entropy term
  model_size: 'lite'
  encoder_size: 'medium'
  dataset_percentage: 1.0